version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - cities_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=cities_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  redis_db:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/redis.conf
      - cities_redis:/data
    command: [ "redis-server", "/redis.conf" ]
  django-q:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/code
    restart: always
    depends_on:
      - redis_db
  cities:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - django-q
      - redis_db
volumes:
  cities_volume:
  cities_redis:
