# Generated by Django 4.0.3 on 2022-03-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('population_proper', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
